version: "3"

services:
  llmt-workspace:
    image: omhq/llmt-workspace:0.0.5
    working_dir: /workspace
    volumes:
      - ./configs:/workspace/configs
      - ./chats:/workspace/chats
      - ./contexts:/workspace/contexts
      - ./files:/workspace/files
      - ./llmt:/workspace/llmt
      - ./udfs:/workspace/udfs
      - ./examples/simple.py:/workspace/simple.py
      - ./examples/chat.py:/workspace/chat.py
    command: ["chat.py", "-f", "configs/config.yml"]
    environment:
      ROOT_PATH: /workspace
      DEBUG: "true"
