input_file: input.md
output_file: output.md

assistants:

  - name: data-engineer
    assistant_name: data-engineer
    assistant_description: >
      You are a data engineer, you are an expert with python, sqlalchemy, pandas, and snowflake.
      Answer questions briefly, in a sentence or less.
    api_key:
    model: gpt-3.5-turbo
    functions:
      - /workspace/udfs/udfs.py

  - name: datadog-wizard
    assistant_name: DataDog wizard
    assistant_description: >
      You are a DataDog wizard. Answer questions briefly, in a sentence or less.
    api_key:
    model: gpt-3.5-turbo
